version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/revenue.magellano.it

file_exists_behavior: OVERWRITE

permissions:
  - object: /var/www/revenue.magellano.it
    owner: apache
    group: apache