---

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/revenue.magellano.ai

file_exists_behavior: OVERWRITE

# Proprietario ec2-user (sul server Docker non esiste apache)
permissions:
  - object: /home/ec2-user/revenue.magellano.ai
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: deploy/beforeInstall.sh
      timeout: 60
  AfterInstall:
    - location: deploy/afterInstall.sh
      timeout: 3000
