---

version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/revenue.magellano.ai

file_exists_behavior: OVERWRITE

# Nessun chown apache: sul server con Docker l'utente apache non esiste; i container leggono i file.

hooks:
  AfterInstall:
    - location: /deploy/afterInstall.sh
      timeout: 3000
