---

version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/revenue.magellano.ai

file_exists_behavior: OVERWRITE

permissions:
  - object: /var/www/revenue.magellano.ai
    owner: apache
    group: apache

hooks:
  AfterInstall:
    - location: /deploy/afterInstall.sh
      timeout: 3000
