---
version: 0.2

# CodeBuild: solo validazione e upload sorgente.
# Composer, npm e build Docker sono gestiti sul server in afterInstall.sh (via Docker).

phases:
  pre_build:
    commands:
      - echo "Build started on `date`"

  build:
    commands:
      - echo "Validating deployment files..."
      - test -f Dockerfile && echo "✓ Dockerfile found" || (echo "✗ Dockerfile missing"; exit 1)
      - test -f docker-compose.yml && echo "✓ docker-compose.yml found" || (echo "✗ docker-compose.yml missing"; exit 1)
      # Normalizza ownership: evita che l'artifact contenga "apache" (o altri user
      # non presenti sul server) e che l'Install di CodeDeploy fallisca con "can't find user for apache"
      - chown -R root:root .
      - echo "Build completed on `date`"
      - test "$CODEBUILD_BUILD_SUCCEEDING" = "1" || exit 1

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - node_modules/**
    - .git/**
