---
version: 0.2

# CodeBuild: solo validazione e upload sorgente.
# Composer e npm sono nel Dockerfile; build Docker sul server in afterInstall.sh (come deploy_exemple).

phases:
  pre_build:
    commands:
      - echo "Build started on `date`"
      - echo "Validating deployment files..."
      - test -f Dockerfile && echo "✓ Dockerfile found" || (echo "✗ Dockerfile missing"; exit 1)
      - test -f docker-compose.yml && echo "✓ docker-compose.yml found" || (echo "✗ docker-compose.yml missing"; exit 1)
      - test -f composer.json && echo "✓ composer.json found" || (echo "✗ composer.json missing"; exit 1)
      - test -f package.json && echo "✓ package.json found" || (echo "✗ package.json missing"; exit 1)

  build:
    commands:
      # Normalizza ownership: evita che l'artifact contenga user non presenti sul server
      - chown -R root:root .
      - echo "Build completed on `date`"
      - test "$CODEBUILD_BUILD_SUCCEEDING" = "1" || exit 1

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - node_modules/**
    - .git/**
