---
version: 0.2

# Buildspec per agente-magellano-ai
# Semplificato: solo upload codice sorgente
# Il build Docker viene fatto sul server EC2 tramite afterinstall.sh

phases:
  pre_build:
    commands:
      - echo "Build started on `date`"
      - echo "Preparing source code for deployment..."

  build:
    commands:
      - echo "Validating source code..."
      - test -f Dockerfile && echo "✓ Dockerfile found" || echo "✗ Dockerfile missing"
      - test -f docker-compose.yml && echo "✓ docker-compose.yml found" || echo "✗ docker-compose.yml missing"
      - test -f package.json && echo "✓ package.json found" || echo "✗ package.json missing"

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Source code ready for deployment"
      - test "$CODEBUILD_BUILD_SUCCEEDING" = "1" || exit 1

artifacts:
  files:
    - '**/*'
  exclude-paths:
    - node_modules/**
    - .next/cache/**
    - data/**
    - logs/**
